## Data Cleaning using Pandas

In [3]:
# importing the required packages 
import pandas as pd

In [4]:

df = pd.read_csv(r"C:\Users\lenovo\Downloads\indian toys\indian_toy_market_sales_data.csv")
df.head()

,Transaction_ID,Transaction_Date,Year,Month,Month_Name,Quarter,Day_of_Week,Brand,Brand_Type,Product_Category,...,Unit_Price_INR,Quantity,Gross_Revenue_INR,Discount_Percentage,Discount_Amount_INR,Net_Revenue_INR,Customer_Rating,Safety_Certified,Returned,Customer_Type
0,TXN-20230802-000000,2023-08-02,2023,8,August,Q3,Wednesday,OKPlay,Local,STEM Toys,...,3309.05,4,13236.20,0.0,0.0,13236.20,3.4,TRUE,no,New
1,TXN-20240412-000001,2024-04-12,2024,4,April,Q2,Friday,Lego,International,Arts & Crafts,...,602.82,3,1808.46,0.0,0.0,1808.46,4.1,NaN,no,Returning
2,TXN-20220128-000002,2022-01-28,2022,1,January,Q1,Friday,Funskool India,International,Board Games,...,3171.93,1,3171.93,0.0,0.0,3171.93,4.3,TRUE,Yes,Returning
3,TXN-20201012-000003,2020-10-12,2020,10,October,Q4,Monday,HASBRO,International,Soft Toys,...,1756.13,1,1756.13,0.0,0.0,1756.13,3.6,yes,yes,Returning
4,TXN-20211127-000004,2021-11-27,2021,11,November,Q4,Saturday,Fisher Price,International,Construction Toys,...,3616.34,2,7232.68,0.0,0.0,7232.68,4.7,No,no,Returning

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Transaction_ID       100000 non-null  object
 1   Transaction_Date     100000 non-null  object
 2   Year                 100000 non-null  int64
 3   Month                100000 non-null  int64
 4   Month_Name           100000 non-null  object
 5   Quarter              100000 non-null  object
 6   Day_of_Week          100000 non-null  object
 7   Brand                100000 non-null  object
 8   Brand_Type           100000 non-null  object
 9   Product_Category     100000 non-null  object
 10  Product_Subcategory  100000 non-null  object
 11  Product_ID           100000 non-null  object
 12  Region               98968 non-null   object
 13  City                 100000 non-null  object
 14  City_Tier            100000 non-null  object
 15  Sales_Channel        100000 non-null  object
 16  Channel_Type         100000 non-null  object
 17  Target_Age_Group     100000 non-null  object
 18  Unit_Price_INR       100000 non-null  float64
 19  Quantity             100000 non-null  int64
 20  Gross_Revenue_INR    100000 non-null  float64
 21  Discount_Percentage  100000 non-null  float64
 22  Discount_Amount_INR  100000 non-null  float64
 23  Net_Revenue_INR      100000 non-null  float64
 24  Customer_Rating      98021 non-null   float64
 25  Safety_Certified     89984 non-null   object
 26  Returned             95044 non-null   object
 27  Customer_Type        97032 non-null   object
dtypes: float64(6), int64(3), object(19)
memory usage: 21.4+ MB

In [6]:
print(df.columns)

Index(['Transaction_ID', 'Transaction_Date', 'Year', 'Month', 'Month_Name',
       'Quarter', 'Day_of_Week', 'Brand', 'Brand_Type', 'Product_Category',
       'Product_Subcategory', 'Product_ID', 'Region', 'City', 'City_Tier',
       'Sales_Channel', 'Channel_Type', 'Target_Age_Group', 'Unit_Price_INR',
       'Quantity', 'Gross_Revenue_INR', 'Discount_Percentage',
       'Discount_Amount_INR', 'Net_Revenue_INR', 'Customer_Rating',
       'Safety_Certified', 'Returned', 'Customer_Type'],
      dtype='object')

In [7]:
# changing column names to snake case
df.columns = df.columns.str.lower()

In [8]:
df.head()

,transaction_id,transaction_date,year,month,month_name,quarter,day_of_week,brand,brand_type,product_category,...,unit_price_inr,quantity,gross_revenue_inr,discount_percentage,discount_amount_inr,net_revenue_inr,customer_rating,safety_certified,returned,customer_type
0,TXN-20230802-000000,2023-08-02,2023,8,August,Q3,Wednesday,OKPlay,Local,STEM Toys,...,3309.05,4,13236.20,0.0,0.0,13236.20,3.4,TRUE,no,New
1,TXN-20240412-000001,2024-04-12,2024,4,April,Q2,Friday,Lego,International,Arts & Crafts,...,602.82,3,1808.46,0.0,0.0,1808.46,4.1,NaN,no,Returning
2,TXN-20220128-000002,2022-01-28,2022,1,January,Q1,Friday,Funskool India,International,Board Games,...,3171.93,1,3171.93,0.0,0.0,3171.93,4.3,TRUE,Yes,Returning
3,TXN-20201012-000003,2020-10-12,2020,10,October,Q4,Monday,HASBRO,International,Soft Toys,...,1756.13,1,1756.13,0.0,0.0,1756.13,3.6,yes,yes,Returning
4,TXN-20211127-000004,2021-11-27,2021,11,November,Q4,Saturday,Fisher Price,International,Construction Toys,...,3616.34,2,7232.68,0.0,0.0,7232.68,4.7,No,no,Returning

In [9]:
df['safety_certified'] = df['safety_certified'].map({'TRUE': 'Yes',
                                                     'yes': 'Yes', 
                                                     'No':'No', 
                                                     'N':'No', 
                                                     'Y':'Yes', 
                                                     'no': 'No', 
                                                     'Yes':'Yes', 
                                                     'FALSE': 'No'})
print(f'safety_certified column cleaned.')

safety_certified column cleaned.

In [10]:
df['safety_certified'].unique()

array(['Yes', nan, 'No'], dtype=object)

### Brand column

In [11]:
# cleaning the brand column 
df['brand'].unique()

array(['OKPlay', ' Lego ', 'Funskool India', 'HASBRO', 'Fisher Price',
       'Lego', 'Nerf', 'HotWheels', 'Toyzone', 'OK Play', 'Hot Wheels',
       'Barbie', 'Funskool', 'Hasbro', 'Skillmatics', 'Toy Zone', 'NERF',
       'LEGO', 'BARBIE', 'Playshifu', 'Mattel', 'Fisher-Price', 'MATTEL',
       ' Playshifu ', ' Skillmatics ', ' Hot Wheels ', ' Barbie ',
       ' Hasbro ', ' Smartivity ', ' BARBIE ', 'Smartivity', ' MATTEL ',
       ' Toy Zone ', ' Toyzone ', ' Funskool India ', ' OK Play ',
       ' HotWheels ', ' Funskool ', ' Mattel ', ' Nerf ', ' NERF ',
       ' LEGO ', ' OKPlay ', ' Fisher Price ', ' Fisher-Price ',
       ' HASBRO '], dtype=object)

In [12]:
# trimming the right and left spaces 
df['brand'] = (df['brand'].str.strip())

In [13]:
df['brand'].unique()

array(['OKPlay', 'Lego', 'Funskool India', 'HASBRO', 'Fisher Price',
       'Nerf', 'HotWheels', 'Toyzone', 'OK Play', 'Hot Wheels', 'Barbie',
       'Funskool', 'Hasbro', 'Skillmatics', 'Toy Zone', 'NERF', 'LEGO',
       'BARBIE', 'Playshifu', 'Mattel', 'Fisher-Price', 'MATTEL',
       'Smartivity'], dtype=object)

In [14]:
df['brand'] = df['brand'].map({'OKPlay' : 'OK Play',
                       'Funskool India' : 'Funskool', 
                       'Lego' : 'Lego',
                       'Fisher Price': 'Fisher Price',
                       'HASBRO':'Hasbro', 
                       'Nerf' : 'Nerf',
                       'Funskool' : 'Funskool',
                       'OK Play' : 'OK Play',
                       'Hot Wheels' : 'Hot Wheels',
                       'Barbie' : 'Barbie',
                       'Hasbro' : 'Hasbro', 
                       'Skillmatics' : 'Skillmatics',
                       'Toy Zone' : 'Toy Zone',
                       'Playshifu' : 'Playshifu',
                       'Mattel' : 'Mattel',
                       'Smartivity': 'Smartivity',
                       'HotWheels' : 'Hot Wheels', 
                       'Toyzone' : 'Toy Zone',  
                       'NERF' : 'Nerf', 
                       'LEGO' : 'Lego',
                       'BARBIE' :'Barbie', 
                       'Fisher-Price' : 'Fisher Price', 
                       'MATTEL' : 'Mattel',
                       })

In [15]:
df['brand'].unique()

array(['OK Play', 'Lego', 'Funskool', 'Hasbro', 'Fisher Price', 'Nerf',
       'Hot Wheels', 'Toy Zone', 'Barbie', 'Skillmatics', 'Playshifu',
       'Mattel', 'Smartivity'], dtype=object)

### city column

In [16]:
df['city'].unique()

array(['Delhi', 'Kolkata', 'Calcutta', 'Coimbatore', 'Noida', 'Gurugram',
       'Kochi', 'Chandigarh', ' Kochi', 'Chennai', 'Bengaluru', ' Noida',
       'Patna', 'Indore', 'Mumbai', ' Hyderabad', 'Bombay', ' Calcutta',
       ' Kolkata', 'Ranchi', 'Ahmedabad', 'Mysore', 'Jaipur', 'Guwahati',
       'Nagpur', 'Bangalore', 'Hyderabad', 'Pune', 'Surat', ' Ranchi',
       'Bhubaneswar', 'Lucknow', ' Bengaluru', ' Coimbatore', ' Delhi',
       ' Mysore', ' Guwahati', ' Surat', ' Chennai', ' Jaipur', ' Bombay',
       ' Pune', ' Nagpur', ' Lucknow', ' Patna', ' Bhubaneswar',
       ' Mumbai', ' Bangalore', ' Gurugram', ' Indore', ' Ahmedabad',
       ' Chandigarh'], dtype=object)

In [17]:
# cleaning the city column 
df['city'] = df['city'].str.strip()

In [18]:
city_rename = {
    'Calcutta': 'Kolkata',
    'Bombay': 'Mumbai',
    'Bangalore': 'Bengaluru'
}
df['city'] = df['city'].replace(city_rename)

#### sales_channel column

In [19]:
df['sales_channel'].unique()

array(['Hamleys Store', 'flipkart', 'amazon.in', 'Hamleys', 'Amazon',
       'Brand Website', 'Retail Chain', 'Local Toy Store', 'Flipkart',
       'Website', 'FirstCry'], dtype=object)

In [20]:
# cleaning the sales_channel column 
channel_replace = {
    'Hamleys':'Hamleys Store',
    'amazon.in': 'Amazon',
    'flipkart' : 'Flipkart',
    'Website' : 'Brand Website'
}
df['sales_channel'] = df['sales_channel'].replace(channel_replace)

#### target_age_group column

In [21]:
df['target_age_group'].unique()

array(['13+', '9-12', '6-8 years', '13+ years', '3-5 years', '6-8', '0-2',
       '9-12 years', '0-2 years', '3-5'], dtype=object)

In [22]:
age_group_replace = {
    '0-2' : '0-2 years',
    '3-5' : '3-5 years', 
    '6-8' : '6-8 years',
    '9-12' : '9-12 years',
    '13+' : '13+ years' 
}
df['target_age_group']= df['target_age_group'].replace(age_group_replace)

#### Quantity column

In [23]:
df['quantity'].unique()

array([ 4,  3,  1,  2, -1,  5, -2, -4, -3, -5])

In [24]:
df['quantity'] = df['quantity'].abs()

####  returned column

In [25]:
df['returned'].unique()

array(['no', 'Yes', 'yes', 'N', 'Y', 'No', nan], dtype=object)

In [26]:
returned_std = {
    'yes' : 'Yes',
    'Y' : 'Yes',
    'N' : 'No',
    'no' : 'No'
}
df['returned'] = df['returned'].replace(returned_std)

#### unit_price_inr column

In [ ]:
# unit_price_inr column
df['unit_price_inr'] = df['unit_price_inr'].abs()

### Regions data column

In [31]:
print(df['region'].unique())

['North' 'East' 'South' 'West' nan]

In [32]:
import duckdb
import pandas as pd

df = pd.read_csv(r"C:\Users\lenovo\Downloads\indian toys\cleaned_indian_toy_market_sales_data.csv")

query = """
SELECT DISTINCT city, region
FROM df
WHERE region = 'West'
GROUP BY city, region

-- LIMIT 30
"""

result = duckdb.query(query).to_df()
result

        city region
0     Indore   West
1     Mumbai   West
2       Pune   West
3  Ahmedabad   West
4     Nagpur   West
5      Surat   West

In [33]:
regions_dict = {
    'South':['Kochi', 'Mysore','Coimbatore','Bengaluru', 'Hyderabad', 'Chennai' ], 
    'North' : ['Delhi', 'Noida', 'Chandigarh', 'Gurugram','Jaipur', 'Lucknow' ],
    'East' : ['Patna', 'Kolkata', 'Guwahati', 'Ranchi', 'Bhubaneswar'],
    'West' : ['Indore', 'Mumbai', 'Pune', 'Surat', 'Ahmedabad', 'Nagpur']
}


# Reverse mapping: city -> region
regions_cities = {
    city : region
    for region, cities in regions_dict.items()
    for city in cities
}

# Fill only rows where region is NaN
mask = df['region'].isna()

df.loc[mask, 'region'] = (
    df.loc[mask, 'city']
      .astype(str)
      .map(regions_cities)
)

#### cleaning the date column

In [34]:
print(df['transaction_date'].head(10))

0    2023-08-02
1    2024-04-12
2    2022-01-28
3    2020-10-12
4    2021-11-27
5    2021-05-05
6    2020-02-13
7    2020-07-20
8    2022-02-15
9    2020-09-02
Name: transaction_date, dtype: object

In [35]:
# replacing / with - to standardize the transaction_date column 
df['transaction_date'] = df['transaction_date'].str.replace('/', '-')
df['transaction_date'] = pd.to_datetime(df['transaction_date'], format = 'mixed', dayfirst=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaction_id       100000 non-null  object
 1   transaction_date     100000 non-null  datetime64[ns]
 2   year                 100000 non-null  int64
 3   month                100000 non-null  int64
 4   month_name           100000 non-null  object
 5   quarter              100000 non-null  object
 6   day_of_week          100000 non-null  object
 7   brand                100000 non-null  object
 8   brand_type           100000 non-null  object
 9   product_category     100000 non-null  object
 10  product_subcategory  100000 non-null  object
 11  product_id           100000 non-null  object
 12  region               100000 non-null  object
 13  city                 100000 non-null  object
 14  city_tier            100000 non-null  object
 15  sales_channel        100000 non-null  object
 16  channel_type         100000 non-null  object
 17  target_age_group     100000 non-null  object
 18  unit_price_inr       100000 non-null  float64
 19  quantity             100000 non-null  int64
 20  gross_revenue_inr    100000 non-null  float64
 21  discount_percentage  100000 non-null  float64
 22  discount_amount_inr  100000 non-null  float64
 23  net_revenue_inr      100000 non-null  float64
 24  customer_rating      98021 non-null   float64
 25  safety_certified     89984 non-null   object
 26  returned             95044 non-null   object
 27  customer_type        97032 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(3), object(18)
memory usage: 21.4+ MB

In [37]:
# printing duplicates from the data 
print(df[df.duplicated()])

Empty DataFrame
Columns: [transaction_id, transaction_date, year, month, month_name, quarter, day_of_week, brand, brand_type, product_category, product_subcategory, product_id, region, city, city_tier, sales_channel, channel_type, target_age_group, unit_price_inr, quantity, gross_revenue_inr, discount_percentage, discount_amount_inr, net_revenue_inr, customer_rating, safety_certified, returned, customer_type]
Index: []

[0 rows x 28 columns]

In [39]:
print(df.tail())

            transaction_id transaction_date  year  month month_name quarter  \
99995  TXN-20200501-099995       2020-05-01  2020      5        May      Q2
99996  TXN-20201215-099996       2020-12-15  2020     12   December      Q4
99997  TXN-20210815-099997       2021-08-15  2021      8     August      Q3
99998  TXN-20220905-099998       2022-05-09  2022      9  September      Q3
99999  TXN-20210111-099999       2021-01-11  2021      1    January      Q1

      day_of_week         brand     brand_type product_category  ...  \
99995      Friday       OK Play          Local        Soft Toys  ...
99996     Tuesday     Playshifu          Local    Arts & Crafts  ...
99997      Sunday     Playshifu          Local        Soft Toys  ...
99998      Monday        Mattel  International         Vehicles  ...
99999      Monday  Fisher Price  International    Arts & Crafts  ...

      unit_price_inr quantity gross_revenue_inr discount_percentage  \
99995        2199.14        1           2199.14                0.00
99996        1809.36        1           1809.36                0.00
99997        1180.04        2           2360.08                0.00
99998        5055.06        1           5055.06                0.00
99999         944.60        1            944.60               11.38

      discount_amount_inr net_revenue_inr customer_rating safety_certified  \
99995                 0.0         2199.14             4.3               No
99996                 0.0         1809.36             4.4              Yes
99997                 0.0         2360.08             4.5               No
99998                 0.0         5055.06             4.8              Yes
99999               107.5          837.10             4.3               No

       returned  customer_type
99995        No            New
99996        No      Returning
99997       Yes      Returning
99998       Yes      Returning
99999        No            NaN

[5 rows x 28 columns]

In [38]:
# downloading the cleaned data 
df.to_csv(r"C:\Users\lenovo\Downloads\indian toys\cleaned_indian_toy_market_sales_data.csv", index= False)